# Form implementation generated from reading ui file 'charaAdd.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CharaEdit(object):
    def setupUi(self, CharaEdit):
        CharaEdit.setObjectName("CharaEdit")
        CharaEdit.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        CharaEdit.resize(500, 400)
        self.btnDialogEditExit = QtWidgets.QPushButton(CharaEdit)
        self.btnDialogEditExit.setGeometry(QtCore.QRect(390, 360, 101, 24))
        self.btnDialogEditExit.setObjectName("btnDialogEditExit")
        self.btnDialogEditDefine = QtWidgets.QPushButton(CharaEdit)
        self.btnDialogEditDefine.setGeometry(QtCore.QRect(260, 360, 101, 24))
        self.btnDialogEditDefine.setObjectName("btnDialogEditDefine")
        self.listWidget = QtWidgets.QListWidget(CharaEdit)
        self.listWidget.setGeometry(QtCore.QRect(260, 40, 231, 301))
        self.listWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.btnAddChara = QtWidgets.QPushButton(CharaEdit)
        self.btnAddChara.setGeometry(QtCore.QRect(340, 10, 71, 24))
        self.btnAddChara.setObjectName("btnAddChara")
        self.btnDelChara = QtWidgets.QPushButton(CharaEdit)
        self.btnDelChara.setGeometry(QtCore.QRect(420, 10, 71, 24))
        self.btnDelChara.setObjectName("btnDelChara")
        self.charaTag = QtWidgets.QLineEdit(CharaEdit)
        self.charaTag.setGeometry(QtCore.QRect(10, 30, 113, 20))
        self.charaTag.setPlaceholderText("")
        self.charaTag.setObjectName("charaTag")
        self.label01 = QtWidgets.QLabel(CharaEdit)
        self.label01.setGeometry(QtCore.QRect(30, 10, 71, 16))
        self.label01.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label01.setObjectName("label01")
        self.label01_2 = QtWidgets.QLabel(CharaEdit)
        self.label01_2.setGeometry(QtCore.QRect(150, 10, 71, 16))
        self.label01_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label01_2.setObjectName("label01_2")
        self.charaName = QtWidgets.QLineEdit(CharaEdit)
        self.charaName.setGeometry(QtCore.QRect(130, 30, 113, 20))
        self.charaName.setPlaceholderText("")
        self.charaName.setObjectName("charaName")
        self.verticalLayoutWidget = QtWidgets.QWidget(CharaEdit)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 120, 211, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label01_3 = QtWidgets.QLabel(CharaEdit)
        self.label01_3.setGeometry(QtCore.QRect(90, 60, 71, 16))
        self.label01_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label01_3.setObjectName("label01_3")
        self.charaPrefix = QtWidgets.QLineEdit(CharaEdit)
        self.charaPrefix.setGeometry(QtCore.QRect(50, 80, 151, 20))
        self.charaPrefix.setPlaceholderText("")
        self.charaPrefix.setObjectName("charaPrefix")
        self.btnDefineChara = QtWidgets.QPushButton(CharaEdit)
        self.btnDefineChara.setGeometry(QtCore.QRect(260, 10, 71, 24))
        self.btnDefineChara.setObjectName("btnDefineChara")

        self.retranslateUi(CharaEdit)
        QtCore.QMetaObject.connectSlotsByName(CharaEdit)

    def retranslateUi(self, CharaEdit):
        _translate = QtCore.QCoreApplication.translate
        CharaEdit.setWindowTitle(_translate("CharaEdit", "人物编辑"))
        self.btnDialogEditExit.setText(_translate("CharaEdit", "取消"))
        self.btnDialogEditDefine.setText(_translate("CharaEdit", "确定"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("CharaEdit", "Test"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.btnAddChara.setText(_translate("CharaEdit", "添加"))
        self.btnDelChara.setText(_translate("CharaEdit", "删除"))
        self.label01.setText(_translate("CharaEdit", "人物识别名"))
        self.label01_2.setText(_translate("CharaEdit", "显示名"))
        self.label01_3.setText(_translate("CharaEdit", "立绘前缀"))
        self.btnDefineChara.setText(_translate("CharaEdit", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CharaEdit = QtWidgets.QWidget()
    ui = Ui_CharaEdit()
    ui.setupUi(CharaEdit)
    CharaEdit.show()
    sys.exit(app.exec())
