# Form implementation generated from reading ui file 'editPicList.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_picEdit(object):
    def setupUi(self, picEdit):
        picEdit.setObjectName("picEdit")
        picEdit.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        picEdit.resize(704, 352)
        self.picPathEdit = QtWidgets.QLineEdit(picEdit)
        self.picPathEdit.setEnabled(False)
        self.picPathEdit.setGeometry(QtCore.QRect(60, 20, 231, 24))
        self.picPathEdit.setObjectName("picPathEdit")
        self.label = QtWidgets.QLabel(picEdit)
        self.label.setGeometry(QtCore.QRect(0, 10, 55, 41))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.btnOpenFileMana = QtWidgets.QPushButton(picEdit)
        self.btnOpenFileMana.setGeometry(QtCore.QRect(300, 20, 24, 24))
        self.btnOpenFileMana.setObjectName("btnOpenFileMana")
        self.btnCancel = QtWidgets.QPushButton(picEdit)
        self.btnCancel.setGeometry(QtCore.QRect(350, 320, 75, 22))
        self.btnCancel.setObjectName("btnCancel")
        self.btnDefine = QtWidgets.QPushButton(picEdit)
        self.btnDefine.setGeometry(QtCore.QRect(260, 320, 75, 22))
        self.btnDefine.setObjectName("btnDefine")
        self.doubleSpinBoxSize = QtWidgets.QDoubleSpinBox(picEdit)
        self.doubleSpinBoxSize.setGeometry(QtCore.QRect(70, 320, 62, 22))
        self.doubleSpinBoxSize.setObjectName("doubleSpinBoxSize")
        self.label_2 = QtWidgets.QLabel(picEdit)
        self.label_2.setGeometry(QtCore.QRect(10, 320, 55, 22))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btnReload = QtWidgets.QPushButton(picEdit)
        self.btnReload.setGeometry(QtCore.QRect(170, 320, 75, 22))
        self.btnReload.setObjectName("btnReload")
        self.labelPic = QtWidgets.QLabel(picEdit)
        self.labelPic.setGeometry(QtCore.QRect(30, 60, 384, 216))
        self.labelPic.setText("")
        self.labelPic.setObjectName("labelPic")
        self.btnAdd = QtWidgets.QPushButton(picEdit)
        self.btnAdd.setEnabled(True)
        self.btnAdd.setGeometry(QtCore.QRect(330, 20, 50, 24))
        self.btnAdd.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.btnAdd.setObjectName("btnAdd")
        self.tableView = QtWidgets.QTableView(picEdit)
        self.tableView.setGeometry(QtCore.QRect(440, 20, 251, 321))
        self.tableView.setObjectName("tableView")
        self.btnDelete = QtWidgets.QPushButton(picEdit)
        self.btnDelete.setEnabled(True)
        self.btnDelete.setGeometry(QtCore.QRect(385, 20, 50, 24))
        self.btnDelete.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.btnDelete.setObjectName("btnDelete")

        self.retranslateUi(picEdit)
        QtCore.QMetaObject.connectSlotsByName(picEdit)

    def retranslateUi(self, picEdit):
        _translate = QtCore.QCoreApplication.translate
        picEdit.setWindowTitle(_translate("picEdit", "编辑图片列表"))
        self.label.setText(_translate("picEdit", "图片路径"))
        self.btnOpenFileMana.setText(_translate("picEdit", "..."))
        self.btnCancel.setText(_translate("picEdit", "取消"))
        self.btnDefine.setText(_translate("picEdit", "确定"))
        self.label_2.setText(_translate("picEdit", "大小"))
        self.btnReload.setText(_translate("picEdit", "加载"))
        self.btnAdd.setText(_translate("picEdit", "添加"))
        self.btnDelete.setText(_translate("picEdit", "删除"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    picEdit = QtWidgets.QWidget()
    ui = Ui_picEdit()
    ui.setupUi(picEdit)
    picEdit.show()
    sys.exit(app.exec())
