# Form implementation generated from reading ui file 'picAdd.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_picAdd(object):
    def setupUi(self, picAdd):
        picAdd.setObjectName("picAdd")
        picAdd.resize(446, 352)
        self.picPathEdit = QtWidgets.QLineEdit(picAdd)
        self.picPathEdit.setGeometry(QtCore.QRect(90, 20, 231, 24))
        self.picPathEdit.setObjectName("picPathEdit")
        self.label = QtWidgets.QLabel(picAdd)
        self.label.setGeometry(QtCore.QRect(20, 20, 55, 24))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.btnOpenFileMana = QtWidgets.QPushButton(picAdd)
        self.btnOpenFileMana.setGeometry(QtCore.QRect(340, 20, 31, 24))
        self.btnOpenFileMana.setObjectName("btnOpenFileMana")
        self.btnCancel = QtWidgets.QPushButton(picAdd)
        self.btnCancel.setGeometry(QtCore.QRect(330, 320, 75, 22))
        self.btnCancel.setObjectName("btnCancel")
        self.btnDefine = QtWidgets.QPushButton(picAdd)
        self.btnDefine.setGeometry(QtCore.QRect(240, 320, 75, 22))
        self.btnDefine.setObjectName("btnDefine")
        self.doubleSpinBoxSize = QtWidgets.QDoubleSpinBox(picAdd)
        self.doubleSpinBoxSize.setGeometry(QtCore.QRect(70, 320, 62, 22))
        self.doubleSpinBoxSize.setObjectName("doubleSpinBoxSize")
        self.label_2 = QtWidgets.QLabel(picAdd)
        self.label_2.setGeometry(QtCore.QRect(10, 320, 55, 22))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btnReload = QtWidgets.QPushButton(picAdd)
        self.btnReload.setGeometry(QtCore.QRect(150, 320, 75, 22))
        self.btnReload.setObjectName("btnReload")
        self.labelPic = QtWidgets.QLabel(picAdd)
        self.labelPic.setGeometry(QtCore.QRect(30, 60, 384, 216))
        self.labelPic.setText("")
        self.labelPic.setObjectName("labelPic")

        self.retranslateUi(picAdd)
        QtCore.QMetaObject.connectSlotsByName(picAdd)

    def retranslateUi(self, picAdd):
        _translate = QtCore.QCoreApplication.translate
        picAdd.setWindowTitle(_translate("picAdd", "添加图片"))
        self.label.setText(_translate("picAdd", "图片路径"))
        self.btnOpenFileMana.setText(_translate("picAdd", "..."))
        self.btnCancel.setText(_translate("picAdd", "取消"))
        self.btnDefine.setText(_translate("picAdd", "确定"))
        self.label_2.setText(_translate("picAdd", "大小"))
        self.btnReload.setText(_translate("picAdd", "加载"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    picAdd = QtWidgets.QWidget()
    ui = Ui_picAdd()
    ui.setupUi(picAdd)
    picAdd.show()
    sys.exit(app.exec())
