# Form implementation generated from reading ui file 'videoAdd.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VideoAdd(object):
    def setupUi(self, VideoAdd):
        VideoAdd.setObjectName("VideoAdd")
        VideoAdd.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        VideoAdd.resize(416, 145)
        self.chooseVideo = QtWidgets.QLineEdit(VideoAdd)
        self.chooseVideo.setEnabled(False)
        self.chooseVideo.setGeometry(QtCore.QRect(80, 41, 291, 20))
        self.chooseVideo.setObjectName("chooseVideo")
        self.label = QtWidgets.QLabel(VideoAdd)
        self.label.setGeometry(QtCore.QRect(10, 41, 55, 20))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.btnOpenFileMana = QtWidgets.QPushButton(VideoAdd)
        self.btnOpenFileMana.setGeometry(QtCore.QRect(380, 39, 24, 24))
        self.btnOpenFileMana.setObjectName("btnOpenFileMana")
        self.btnDefine = QtWidgets.QPushButton(VideoAdd)
        self.btnDefine.setGeometry(QtCore.QRect(240, 100, 75, 24))
        self.btnDefine.setObjectName("btnDefine")
        self.btnCancel = QtWidgets.QPushButton(VideoAdd)
        self.btnCancel.setGeometry(QtCore.QRect(330, 100, 75, 24))
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(VideoAdd)
        QtCore.QMetaObject.connectSlotsByName(VideoAdd)

    def retranslateUi(self, VideoAdd):
        _translate = QtCore.QCoreApplication.translate
        VideoAdd.setWindowTitle(_translate("VideoAdd", "添加视频"))
        self.label.setText(_translate("VideoAdd", "选择文件"))
        self.btnOpenFileMana.setText(_translate("VideoAdd", "..."))
        self.btnDefine.setText(_translate("VideoAdd", "确定"))
        self.btnCancel.setText(_translate("VideoAdd", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VideoAdd = QtWidgets.QWidget()
    ui = Ui_VideoAdd()
    ui.setupUi(VideoAdd)
    VideoAdd.show()
    sys.exit(app.exec())
