# Form implementation generated from reading ui file 'winSettings.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_winSettings(object):
    def setupUi(self, winSettings):
        winSettings.setObjectName("winSettings")
        winSettings.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        winSettings.resize(576, 360)
        self.btnSettingExit = QtWidgets.QPushButton(winSettings)
        self.btnSettingExit.setGeometry(QtCore.QRect(460, 320, 101, 24))
        self.btnSettingExit.setObjectName("btnSettingExit")
        self.btnSettingSave = QtWidgets.QPushButton(winSettings)
        self.btnSettingSave.setGeometry(QtCore.QRect(340, 320, 101, 24))
        self.btnSettingSave.setObjectName("btnSettingSave")
        self.workPathEdit = QtWidgets.QLineEdit(winSettings)
        self.workPathEdit.setGeometry(QtCore.QRect(110, 20, 231, 24))
        self.workPathEdit.setObjectName("workPathEdit")
        self.btnOpenFileMana = QtWidgets.QPushButton(winSettings)
        self.btnOpenFileMana.setGeometry(QtCore.QRect(350, 20, 31, 24))
        self.btnOpenFileMana.setObjectName("btnOpenFileMana")
        self.label = QtWidgets.QLabel(winSettings)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(winSettings)
        QtCore.QMetaObject.connectSlotsByName(winSettings)

    def retranslateUi(self, winSettings):
        _translate = QtCore.QCoreApplication.translate
        winSettings.setWindowTitle(_translate("winSettings", "设置"))
        self.btnSettingExit.setText(_translate("winSettings", "取消"))
        self.btnSettingSave.setText(_translate("winSettings", "保存"))
        self.btnOpenFileMana.setText(_translate("winSettings", "..."))
        self.label.setText(_translate("winSettings", "工作区路径"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    winSettings = QtWidgets.QWidget()
    ui = Ui_winSettings()
    ui.setupUi(winSettings)
    winSettings.show()
    sys.exit(app.exec())
