# Form implementation generated from reading ui file 'DialogEdit.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(285, 344)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(9, 10, 260, 303))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelDialogInput = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDialogInput.setFont(font)
        self.labelDialogInput.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelDialogInput.setObjectName("labelDialogInput")
        self.verticalLayout.addWidget(self.labelDialogInput)
        self.DialogInput = QtWidgets.QPlainTextEdit(self.widget)
        self.DialogInput.setObjectName("DialogInput")
        self.verticalLayout.addWidget(self.DialogInput)
        self.labelChar01 = QtWidgets.QLabel(self.widget)
        self.labelChar01.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelChar01.setObjectName("labelChar01")
        self.verticalLayout.addWidget(self.labelChar01)
        self.comboBoxCharacter = QtWidgets.QComboBox(self.widget)
        self.comboBoxCharacter.setTabletTracking(False)
        self.comboBoxCharacter.setObjectName("comboBoxCharacter")
        self.comboBoxCharacter.addItem("")
        self.verticalLayout.addWidget(self.comboBoxCharacter)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnDialogEditDefine = QtWidgets.QPushButton(self.widget)
        self.btnDialogEditDefine.setObjectName("btnDialogEditDefine")
        self.horizontalLayout.addWidget(self.btnDialogEditDefine)
        self.btnDialogEditExit = QtWidgets.QPushButton(self.widget)
        self.btnDialogEditExit.setObjectName("btnDialogEditExit")
        self.horizontalLayout.addWidget(self.btnDialogEditExit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "添加台词"))
        self.labelDialogInput.setText(_translate("Form", "请输入台词"))
        self.labelChar01.setText(_translate("Form", "人物"))
        self.comboBoxCharacter.setItemText(0, _translate("Form", "测试"))
        self.btnDialogEditDefine.setText(_translate("Form", "确定"))
        self.btnDialogEditExit.setText(_translate("Form", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
