# Form implementation generated from reading ui file 'dialogEdit.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogEditNew(object):
    def setupUi(self, DialogEditNew):
        DialogEditNew.setObjectName("DialogEditNew")
        DialogEditNew.resize(300, 322)
        self.layoutWidget = QtWidgets.QWidget(DialogEditNew)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 258, 299))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.DialogEdit = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.DialogEdit.setObjectName("DialogEdit")
        self.verticalLayout.addWidget(self.DialogEdit)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBoxChara = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxChara.setObjectName("comboBoxChara")
        self.verticalLayout.addWidget(self.comboBoxChara)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnDefine = QtWidgets.QPushButton(self.layoutWidget)
        self.btnDefine.setObjectName("btnDefine")
        self.horizontalLayout.addWidget(self.btnDefine)
        self.btnCancel = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogEditNew)
        QtCore.QMetaObject.connectSlotsByName(DialogEditNew)

    def retranslateUi(self, DialogEditNew):
        _translate = QtCore.QCoreApplication.translate
        DialogEditNew.setWindowTitle(_translate("DialogEditNew", "台词编辑"))
        self.label.setText(_translate("DialogEditNew", "台词编辑"))
        self.label_2.setText(_translate("DialogEditNew", "人物"))
        self.btnDefine.setText(_translate("DialogEditNew", "确定"))
        self.btnCancel.setText(_translate("DialogEditNew", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogEditNew = QtWidgets.QWidget()
    ui = Ui_DialogEditNew()
    ui.setupUi(DialogEditNew)
    DialogEditNew.show()
    sys.exit(app.exec())
